---
# vars for zabbix
zabbix_db_user: "zabbix"
zabbix_db_password: "Qwe123.."
zabbix_db_host: "localhost"
zabbix_db_name: "zabbix"

#vars for deploy
mysql_wordpress_password: 'Abc123..'

domain_name: asirproject.es
wp_site_title: "Asir Project"
wp_admin_user: admin
wp_admin_password: Abc123..
wp_admin_email: "admin@admin.net"
wordpress_path: "/var/www/html/wordpress"