---

- name: Levantar máquinas virtuales en UpCloud
  hosts: localhost
  tasks:
    - name: Crear webserver en UpCloud
      upcloud:
        username: "{{ upcloud_username }}"
        password: "{{ upcloud_password }}"
        hostname: "up-webserver1"
        plan: "1xCPU-1GB"
        zone: "es-mad1"
        template: "Debian 11"
        storage_devices:
          - action: clone
            storage: "Debian 11"
            title: "WebServer Storage"
            size: 20
        networks:
          - type: public
        state: present
      register: up-webserver1

    - name: Crear database en UpCloud
      upcloud:
        username: "{{ upcloud_username }}"
        password: "{{ upcloud_password }}"
        hostname: "up-db1"
        plan: "1xCPU-1GB"
        zone: "es-mad1"
        template: "Debian 11"
        storage_devices:
          - action: clone
            storage: "Debian 11"
            title: "Database storage"
            size: 10
        networks:
          - type: public
        state: present
      register: database

    - name: Crear zabbix en UpCloud
      upcloud:
        username: "{{ upcloud_username }}"
        password: "{{ upcloud_password }}"
        hostname: "up-zabbix1"
        plan: "1xCPU-1GB"
        zone: "es-mad1"
        template: "Debian 11"
        storage_devices:
          - action: clone
            storage: "Debian 11"
            title: "Zabbix storage"
            size: 10
        networks:
          - type: public
        state: present
      register: zabbix

    - name: Mostrar IP de webserver
      debug:
        msg: "Werbserver IP: {{ up-webserver1.data.ip_address }}"

    - name: Mostrar IP de database
      debug:
        msg: "Database IP: {{ up-db1.data.ip_address }}"

    - name: Mostrar IP de zabbix
      debug:
        msg: "Zabbix IP: {{ up-zabbix1.data.ip_address }}"