---
# handlers file for Wordpress

- name: Restart Apache
  systemd:
    name: apache2
    state: restarted

- name: Start Apache
  systemd:
    name: apache2
    state: started

- name: Stop Apache
  systemd:
    name: apache2
    state: stopped

- name: Enable Apache
  systemd:
    name: apache2
    state: enabled

- name: Restart MySQL
  systemd:
    name: mysql
    state: restarted

- name: Start MySQL
  systemd:
    name: mysql
    state: started

- name: Stop MySQL
  systemd:
    name: mysql
    state: stopped

- name: Enable MySQL
  systemd: 
    name: mysql
    enabled: yes

- name: Restart Zabbix
  systemd:
    name: zabbix-server
    state: restarted

- name: Start Zabbix
  systemd:
    name: zabbix-server
    state: started
  
- name: Stop Zabbix
  systemd:
    name: zabbix-server
    state: stopped

- name: Enable Zabbix
  systemd:
    name: zabbix-server
    enabled: yes