---

- name: Descargar y desplegar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
  when: vm_type == "webserver"

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    creates: /var/www/html/wordpress
  when: vm_type == "webserver"

- name: Ajustar permisos para WordPress
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: '0755'
  when: vm_type == "webserver"

- name: Configurar archivo wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
  when: vm_type == "webserver"

- name: Crear la base de datos para WordPress
  mysql_db:
    name: wordpress_db
    state: present
    collation: utf8_general_ci
    encoding: utf8
    login_user: root
  when: vm_name == "up-db"

- name: Crear un usuario para la base de datos
  mysql_user:
    name: wordpress
    password: "{{ mysql_wordpress_password }}"
    host: '10.90.1.%'
    priv: "wordpress_db.*:ALL"
    state: present
    login_user: root
  when: vm_name == "up-db"

- name: Download WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'
  when: vm_type == "webserver"

- name: Install WordPress site
  command: >
    wp core install
    --url="{{ domain_name }}"
    --title="{{ wp_site_title }}"
    --admin_user="{{ wp_admin_user }}"
    --admin_password="{{ wp_admin_password }}"
    --admin_email="{{ wp_admin_email }}"
    --path="{{ wordpress_path }}"
    --allow-root
  args:
    chdir: "{{ wordpress_path }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: wp_installation
  ignore_errors: true
  when: vm_type == "webserver"  