---

- name: Descargar y desplegar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    creates: /var/www/html/wordpress

- name: Ajustar permisos para WordPress
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: '0755'

- name: Configurar archivo wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Instalar mysql-client
  apt:
    name: default-mysql-client
    state: present
    update-cache: yes
  tags:
    - ola