---

- name: Verificar versión de PHP
  shell: php -v
  register: php_version
  when: vm_type == "webserver"
  
- name: Descargar y desplegar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
  when: vm_type == "webserver"

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    creates: /var/www/html/wordpress
  when: vm_type == "webserver"

- name: Ajustar permisos para WordPress
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: '0755'
  when: vm_type == "webserver"

- name: Configurar archivo wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
  when: vm_type == "webserver"

- name: Crear la base de datos para WordPress
  mysql_db:
    name: wordpress_db
    state: present
    collation: utf8_general_ci
    encoding: utf8
    login_user: root
  when: vm_type == "db"

- name: Crear un usuario para la base de datos
  mysql_user:
    name: wordpress
    password: 'Abc123..'
    host: '10.90.1.%'
    priv: "wordpress_db.*:ALL"
    state: present
    login_user: root
  when: vm_type == "db"