---

- name: Instalar Apache
  apt:
    name: apache2
    state: present
    update-cache: yes
  tags:
    - install_zabbix

- name: Habilitar y arrancar Apache
  systemd:
    name: apache2
    enabled: yes
    state: started
  tags:
    - install_zabbix

- name: Comprobar que el servicio Apache está activo
  shell: systemctl status apache2
  register: apache_status
  changed_when: False

- name: Mostrar estado de Apache
  debug:
    var: apache_status.stdout

- name: Habilitar mod_ssl
  command: a2enmod ssl
  notify:
    - Restart Apache
  when: vm_type == "webserver"

- name: Copiar certificado SSL
  copy:
    src: files/cloudflare.pem
    dest: /etc/ssl/certs/cloudflare.pem
    owner: root
    group: root
    mode: 0644

- name: Copiar la clave privada a SSL
  copy:
    src: files/cloudflare.key
    dest: /etc/ssl/private/cloudflare.key
    owner: root
    group: root
    mode: 0600

- name: Crear un archivo de configuración para sitio HTTPS
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - Restart Apache
  when: vm_type == "webserver"

- name: Habilitar el sitio web por defecto
  command: a2ensite 000-default.conf
  notify: 
    - Restart Apache
  when: vm_type == "webserver"