---

- name: Instalar Apache
  apt:
    name: apache2
    state: present
    update-cache: yes
  notify:
    - Enable Apache
    - Start Apache

- name: Habilitar mod_ssl
  command: a2enmod ssl
  notify:
    - Restart Apache
  when: vm_type == "webserver"

- name: Copiar certificado SSL
  copy:
    src: files/{{ domain_name }}.pem
    dest: /etc/ssl/certs/{{ domain_name }}.pem
    owner: root
    group: root
    mode: 0644
  when: vm_type == "webserver"

- name: Copiar la clave privada a SSL
  copy:
    src: files/{{ domain_name }}.key
    dest: /etc/ssl/private/{{ domain_name }}.key
    owner: root
    group: root
    mode: 0600
  when: vm_type == "webserver"

################### Cambiar el habilitar el sitio web por variables####################

- name: Crear un archivo de configuración para sitio HTTPS
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - Restart Apache
  when: vm_type == "webserver"

- name: Habilitar el sitio web por defecto
  command: a2ensite 000-default.conf
  notify: 
    - Restart Apache
  when: vm_type == "webserver"

- name: Configuración para Zabbix
  template:
    src: zabbix_apache.conf.j2
    dest: /etc/apache2/sites-available/zabbix.conf
  notify:
    - Restart Apache
  when: vm_type == "monitoring"

- name: Habilitar el sitio web por defecto en zabbix
  command: a2ensite zabbix.conf
  notify:
    - Restart Apache
  when: vm_type == "monitoring"