---

- name: Instalar el repositorio de Zabbix
  apt:
    name: zabbix-server-mysql
    state: present
    update-cache: yes
  notify:
    - Enable Zabbix
    - Start Zabbix

- name: Mostrar estado de Zabbix
  debug:
    var: zabbix_status.stdout

- name: Crear la base de datos para Zabbix
  mysql_db:
    name: zabbix
    state: present
    collation: utf8_general_ci
    encoding: utf8
    login_user: root
  when: vm_type == "monitoring"

- name: Crear un usuario para la base de datos Zabbix
  mysql_user:
    name: zabbix
    password: 'Qwe123..'
    host: '10.90.1.%'
    priv: "zabbix.*:ALL"
    state: present
    login_user: root
  when: vm_type == "monitoring"
  tags:
    - configure_zabbix