---

- name: Instalar el repositorio de Zabbix
  apt:
    name: zabbix-server-mysql
    state: present
    update-cache: yes
    
- name: Iniciar y habilitar Zabbix
  service:
    name: zabbix-server
    state: started
    enabled: yes

- name: Verificar estado de Zabbix
  shell: systemctl status zabbix-server
  register: zabbix_status
  changed_when: False

- name: Mostrar estado de Zabbix
  debug:
    var: zabbix_status.stdout