---

- name: Download MySQL APT configuration package 
  copy:
    src: files/mysql-apt-config_0.8.30-1_all.deb
    dest: /tmp/mysql-apt-config.deb
  become: yes

- name: Install GnuPG (for package verification)
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Install MySQL APT configuration package
  command: dpkg -i /tmp/mysql-apt-config.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: yes

- name: Update APT cache
  apt:
    update_cache: yes
  become: yes
  
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Iniciar y habilitar MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Instalar módulo de python
  apt:
    name: python3-mysqldb
    state: present
    update-cache: yes

- name: Cargar módulo necesario para Master
  blockinfile:
    path: /etc/mysql/mariadb.cnf
    block: |
      [mysqld]
      mysql_native_password=ON
      server-id = 1
      log-bin = mysql-bin
      binlog-format = ROW
    state: present
  when: vm_name == "up-db"

- name: Cargar módulo necesario para Slave
  blockinfile:
    path: /etc/mysql/mariadb.cnf
    block: | 
      [mysqld]
      mysql_native_password=ON
      server-id = 2
      relay-log = relay-log
  when: vm_name == "up-db-2"

- name: Reiniciar servicio
  service:
    name: mysql
    state: restarted