---

- name: Instalar MySQL
  apt:
    name: default-mysql-server
    state: present
    update-cache: yes

- name: Iniciar y habilitar MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Instalar módulo de python
  apt:
    name: python3-mysqldb
    state: present
    update-cache: yes

- name: Cambiar dirección IP en la que escucha MySQL
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 10.90.1.%'
    state: present
  notify:
    - Restart MySQL

- name: Mostrar estado de MySQL
  debug:
    var: mysql_status.stdout