---

- name: Instalar el repositorio de Zabbix
  apt:
    name: 
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
    state: present
    update-cache: yes
  notify:
    - Start Zabbix
    - Restart Apache

- name: Configurar PHP para Zabbix
  blockinfile:
    path: "/etc/php/7.4/apache2/php.ini"
    marker: "; ANSIBLE MANAGED BLOCK FOR ZABBIX"
    block: |
      post_max_size = 16M
      max_execution_time = 300 
      max_input_time = 300
      date.timezone = "Europe/Madrid"
  notify:
    - Restart Apache

- name: Crear la base de datos para Zabbix
  mysql_db:
    name: "{{ zabbix_db_name }}"
    state: present
    collation: utf8_bin
    encoding: utf8
    login_user: root

- name: Crear un usuario para la base de datos Zabbix
  mysql_user:
    name: "{{ zabbix_db_user }}"
    password: "{{ zabbix_db_password }}"
    host: "{{ zabbix_db_host }}"
    priv: "'{{ zabbix_db_name }}'.*:ALL"
    state: present
    login_user: root

- name: Configurar zabbix_server
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DB(Host|Name|User|Password|Port)='
    line: "{{ item }}"
    create: yes
  loop:
    - "DBHost=l{{ zabbix_db_host }}"
    - "DBName={{ zabbix_db_name }}"
    - "DBUser={{ zabbix_db_user }}"
    - "DBPassword={{zabbix_db_password}}"
  notify:
    - Restart Zabbix

- name: Importar esquema de base de datos para Zabbix
  shell: "/bin/gunzip -c /usr/share/zabbix-server-mysql/*.sql.gz | mysql -u zabbix -pQwe123.. zabbix"
  args:
    executable: /bin/bash