---
# tasks file for wordpress

- name: Install dos2unix package
  apt:
    name: dos2unix
    state: present
    update_cache: yes


- import_tasks: install_mysql.yml
  when: vm_type in ["db", "monitoring"]
  tags:
    - install_mysql

- import_tasks: install_apache.yml
  when: vm_type in ["webserver", "monitoring"]
  tags:
    - install_apache

- import_tasks: install_php.yml
  when: vm_type in ["webserver", "monitoring"]
  tags:
    - install_php

- import_tasks: deploy_site.yml
  when: vm_type in ["webserver", "db"]
  tags:
    - deploy

- import_tasks: install_zabbix.yml
  when: vm_type == "monitoring"
  tags:
    - install_zabbix

- import_tasks: install_zabbix-agent.yml
  tags:
    - install_agent